name: Java Style Check

on:
  pull_request:
    branches:
      - dev
jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: axel-op/googlejavaformat-action@v4
        with:
          args: "--aosp --replace"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: 스타일 수정"
