name: Java Style Check

on: [push]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Run Google Java Format
        uses: axel-op/googlejavaformat-action@v4
        with:
          args: "--aosp --replace" # AOSP 스타일로 포맷 (4칸 들여쓰기)
          commit-message: "fix style"
